[package]
name = "tmlatestbackup"
version = "0.1.0"
authors = ["Borja González Seoane <garaje@glezseoane.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
